export const TITLE_STYLES = [
  {
    description: "Title style 1",
    value: JSON.stringify({
      fontFamily: "Sarasa UI SC",
      fontSize: 80,
      color: "#FFFF00",
      stroke: "#000000",
      strokeThickness: 6,
      align: "center",
    }),
  },
  {
    description: "Title style 2",
    value: JSON.stringify({
      fontFamily: "Sarasa UI SC",
      fontSize: 80,
      color: "#000000",
      stroke: "#000000",
      strokeThickness: 0,
      backgroundColor: "#FFF8DC",
      fontWeight: "bold",
      padding: 20,
      align: "center",
      dropShadow: false,
    }),
  },
  {
    description: "Title style 3",
    value: JSON.stringify({
      fontFamily: "Sarasa UI SC",
      fontSize: 80,
      color: "#FFFFFF",
      stroke: "#000000",
      strokeThickness: 2,
      align: "center",
      dropShadow: true,
      dropShadowColor: "#000000",
      dropShadowBlur: 0,
      dropShadowDistance: 1,
    }),
  },
  {
    description: "Title style 4",
    value: JSON.stringify({
      fontFamily: "Sarasa UI SC",
      fontSize: 80,
      color: "#FFFACD",
      stroke: "#2E8B57",
      strokeThickness: 10,
      align: "center",
      dropShadow: true,
      dropShadowColor: "#2E8B57",
      dropShadowBlur: 0,
      dropShadowDistance: 10,
    }),
  },
  {
    description: "Title style 5",
    value: JSON.stringify({
      fontFamily: "Sarasa UI SC",
      fontSize: 80,
      color: "#FFC107",
      stroke: "#8B0000",
      strokeThickness: 4,
      align: "center",
      dropShadow: true,
      dropShadowColor: "#8B0000",
      dropShadowBlur: 0,
      dropShadowDistance: 8,
    }),
  },
  {
    description: "Title style 6",
    value: JSON.stringify({
      fontFamily: "Sarasa UI SC",
      fontSize: 80,
      color: "#FF69B4",
      stroke: "#000000",
      strokeThickness: 6,
      align: "center",
      dropShadow: true,
      dropShadowColor: "#000000",
      dropShadowBlur: 0,
      dropShadowDistance: 6,
    }),
  },
  {
    description: "Title style 7",
    value: JSON.stringify({
      fontFamily: "Sarasa UI SC",
      fontSize: 80,
      color: "#FF4500",
      stroke: "#000000",
      strokeThickness: 15,
      align: "center",
      dropShadow: true,
      dropShadowColor: "#000000",
      dropShadowBlur: 0,
      dropShadowDistance: 10,
    }),
  },
] as const;

export const SUBTITLE_STYLES = [
  {
    description: "Subtitle style 1",
    value: JSON.stringify({
      fontFamily: "Sarasa UI SC",
      fontSize: 50,
      color: "#FFD700",
      stroke: "#000000",
      strokeThickness: 8,
      align: "center",
      dropShadow: true,
      dropShadowColor: "#000000",
      dropShadowBlur: 2,
      dropShadowDistance: 2,
    }),
  },
  {
    description: "Subtitle style 2",
    value: JSON.stringify({
      fontFamily: "Sarasa UI SC",
      fontSize: 50,
      color: "#FFFFFF",
      stroke: "#000000",
      strokeThickness: 4,
      backgroundColor: "#FF0099",
      padding: 10,
      align: "center",
      dropShadow: false,
    }),
  },
  {
    description: "Subtitle style 3",
    value: JSON.stringify({
      fontFamily: "Sarasa UI SC",
      fontSize: 50,
      color: "#00BFFF",
      stroke: "#000000",
      strokeThickness: 10,
      align: "center",
      dropShadow: true,
      dropShadowColor: "#000000",
      dropShadowBlur: 2,
      dropShadowDistance: 5,
    }),
  },
  {
    description: "Subtitle style 4",
    value: JSON.stringify({
      fontFamily: "Sarasa UI SC",
      fontSize: 50,
      color: "#FFFFFF",
      align: "center",
      dropShadow: true,
      dropShadowColor: "#000000",
      dropShadowDistance: 5,
      dropShadowAngle: 0.78,
      dropShadowBlur: 2,
    }),
  },
  {
    description: "Subtitle style 5",
    value: JSON.stringify({
      fontFamily: "Sarasa UI SC",
      fontSize: 50,
      color: "#FFFFFF",
      stroke: "#000000",
      strokeThickness: 4,
      align: "center",
      dropShadow: true,
      dropShadowColor: "#000000",
      dropShadowBlur: 2,
      dropShadowDistance: 2,
    }),
  },
  {
    description: "Subtitle style 6",
    value: JSON.stringify({
      fontFamily: "Sarasa UI SC",
      fontSize: 50,
      color: "#FFFF00",
      stroke: "#000000",
      strokeThickness: 4,
      align: "center",
      dropShadow: true,
      dropShadowColor: "#000000",
      dropShadowBlur: 2,
      dropShadowDistance: 2,
    }),
  },
  {
    description: "Subtitle style 7",
    value: JSON.stringify({
      fontFamily: "Sarasa UI SC",
      fontSize: 50,
      color: "#FFA500",
      stroke: "#000000",
      strokeThickness: 6,
      align: "center",
      dropShadow: true,
      dropShadowColor: "#000000",
      dropShadowBlur: 2,
      dropShadowDistance: 2,
    }),
  },
  {
    description: "Subtitle style 8",
    value: JSON.stringify({
      fontFamily: "Sarasa UI SC",
      fontSize: 50,
      color: "#00FF7F",
      stroke: "#000000",
      strokeThickness: 8,
      align: "center",
      dropShadow: true,
      dropShadowColor: "#000000",
      dropShadowBlur: 2,
      dropShadowDistance: 5,
    }),
  },
  {
    description: "Subtitle style 9",
    value: JSON.stringify({
      fontFamily: "Sarasa UI SC",
      fontSize: 50,
      color: "#000000",
      stroke: "#FFFFFF",
      strokeThickness: 4,
      align: "center",
      dropShadow: true,
      dropShadowColor: "#000000",
      dropShadowBlur: 2,
      dropShadowDistance: 2,
    }),
  },
] as const;

export const EFFECT_STYLES = [
  {
    url: "https://d3gmxt30r4if5c.cloudfront.net/videos/mini_zoom.mp4",
    description: "Mini zoom",
    value: JSON.stringify({ name: "mini_zoom" }),
  },
  {
    url: "https://d3gmxt30r4if5c.cloudfront.net/videos/ken_burns.mp4",
    description: "Ken burns",
    value: JSON.stringify({ name: "ken_burns" }),
  },
  {
    url: "https://d3gmxt30r4if5c.cloudfront.net/videos/camera_shake.mp4",
    description: "Shake mode",
    value: JSON.stringify({ name: "camera_shake" }),
  },
] as const;

export const TRANSITION_STYLES = [
  ["transition.crossZoom", "CrossZoom", "https://d3gmxt30r4if5c.cloudfront.net/videos/CrossZoom.mp4"],
  ["transition.linearBlur", "LinearBlur", "https://d3gmxt30r4if5c.cloudfront.net/videos/LinearBlur.mp4"],
  ["transition.directionalWarp", "directionalwarp", "https://d3gmxt30r4if5c.cloudfront.net/videos/directionalwarp.mp4"],
  ["transition.rotateScaleFade", "rotate_scale_fade", "https://d3gmxt30r4if5c.cloudfront.net/videos/rotate_scale_fade.mp4"],
  ["transition.fade", "fade", "https://d3gmxt30r4if5c.cloudfront.net/videos/fade.mp4"],
  ["transition.filmBurn", "FilmBurn", "https://d3gmxt30r4if5c.cloudfront.net/videos/FilmBurn.mp4"],
  ["transition.dreamy", "Dreamy", "https://d3gmxt30r4if5c.cloudfront.net/videos/Dreamy.mp4"],
  ["transition.luma", "luma", "https://d3gmxt30r4if5c.cloudfront.net/videos/luma.mp4"],
  ["transition.glitchMemories", "GlitchMemories", "https://d3gmxt30r4if5c.cloudfront.net/videos/GlitchMemories.mp4"],
  ["transition.glitchDisplace", "GlitchDisplace", "https://d3gmxt30r4if5c.cloudfront.net/videos/GlitchDisplace.mp4"],
  ["transition.pixelize", "pixelize", "https://d3gmxt30r4if5c.cloudfront.net/videos/pixelize.mp4"],
  ["transition.cube", "Cube", "https://d3gmxt30r4if5c.cloudfront.net/videos/Cube.mp4"],
  ["transition.windowSlice", "windowslice", "https://d3gmxt30r4if5c.cloudfront.net/videos/windowslice.mp4"],
  ["transition.doorway", "doorway", "https://d3gmxt30r4if5c.cloudfront.net/videos/doorway.mp4"],
  ["transition.gridFlip", "GridFlip", "https://d3gmxt30r4if5c.cloudfront.net/videos/GridFlip.mp4"],
  ["transition.wipeLeft", "wipeLeft", "https://d3gmxt30r4if5c.cloudfront.net/videos/wipeLeft.mp4"],
].map(([label, name, url]) => ({
  label,
  url,
  value: JSON.stringify({ name, duration: 1 }),
})) as ReadonlyArray<{ label: string; url: string; value: string }>;

export const ANIMATION_EFFECTS = {
  subtitle: [
    { name: "fadeInUp", duration: 0.6, delay: 0, desc: "animation.subtitle.fadeInUp" },
    { name: "slideInUp", duration: 0.5, delay: 0, desc: "animation.subtitle.slideInUp" },
    { name: "fadeIn", duration: 0.8, delay: 0, desc: "animation.subtitle.fadeIn" },
    { name: "backInUp", duration: 0.8, delay: 0, desc: "animation.subtitle.backInUp" },
  ],
  title: [
    { name: "backInDown", duration: 1.2, delay: 0.3, desc: "animation.title.backInDown" },
    { name: "zoomInDown", duration: 1.0, delay: 0.2, desc: "animation.title.zoomInDown" },
    { name: "fadeInDown", duration: 1.2, delay: 0.2, desc: "animation.title.fadeInDown" },
    { name: "zoomIn", duration: 1.2, delay: 0.2, desc: "animation.title.zoomIn" },
    { name: "slideInRight", duration: 1.0, delay: 0.1, desc: "animation.title.slideInRight" },
  ],
} as const;
